packages:
  - 'packages/*'
  - 'auth-service'
  - 'auth-service-e2e'
  - 'order-service'
  - 'order-service-e2e'
  - 'shared'
  - 'payment-service'
  - 'payment-service-e2e'
  - 'checkout-service'
  - 'checkout-service-e2e'
allowBuilds:
  '@parcel/watcher': true
  less: true
  protobufjs: true
  unrs-resolver: true
  '@swc/core': true
  'nx': true
